source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.2.0"

# Rails framework
gem "rails", "~> 7.1.0"

# Database
gem "pg", "~> 1.1"
gem "activerecord-postgis-adapter", "~> 8.0"

# Redis for caching and jobs
gem "redis", "~> 5.0"
gem "sidekiq", "~> 7.0"

# Web server
gem "puma", "~> 6.0"

# Asset pipeline
gem "sassc-rails", ">= 2.1.0"
gem "image_processing", "~> 1.2"

# JavaScript/CSS
gem "importmap-rails"
gem "turbo-rails"
gem "stimulus-rails"
gem "jbuilder"

# File uploads and AWS
gem "aws-sdk-s3", "~> 1.100"
gem "image_processing", "~> 1.2"

# XML/KML parsing
gem "nokogiri", "~> 1.15"

# Geospatial
gem "rgeo", "~> 3.0"
gem "rgeo-geojson", "~> 2.1"

# Authentication & Authorization
gem "devise", "~> 4.9"
gem "cancancan", "~> 3.5"

# Forms and validation
gem "simple_form", "~> 5.3"

# Bootstrap styling
gem "bootstrap", "~> 5.3"
gem "jquery-rails"

# Use Redis adapter to run Action Cable in production
gem "redis-actioncable"

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", require: false

group :development, :test do
  # Debugging
  gem "debug", platforms: %i[ mri mingw x64_mingw ]
  
  # Testing
  gem "rspec-rails", "~> 6.0"
  gem "factory_bot_rails", "~> 6.4"
  gem "faker", "~> 3.2"
end

group :development do
  # Development tools
  gem "web-console"
  gem "listen", "~> 3.3"
  gem "spring"
  
  # Code quality
  gem "rubocop-rails", require: false
  gem "brakeman", require: false
end

group :test do
  gem "capybara", ">= 3.26"
  gem "selenium-webdriver"
  gem "webdrivers"
  gem "shoulda-matchers", "~> 5.3"
end