// Slice 6 — WCB queue support in billing workspace frontend tests.
//
// Covers: filter chip renders, clicking chip fires ?type=wcb,
// WCB row renders with number/customer/tech, Approve button hidden
// for billing_manager, Approve button dispatches to the wet check
// approve endpoint for manager roles.

import { describe, it, expect, vi, beforeEach } from 'vitest';
import { render, screen, fireEvent, waitFor, act } from '@testing-library/react';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { TooltipProvider } from '@/components/ui/tooltip';

vi.mock('@/lib/impersonation', () => ({
  getImpersonationToken: () => null,
  getCurrentUser: vi.fn(() => ({ id: 1, username: 'mgr', role: 'company_admin' })),
}));
vi.mock('@/utils/safeStorage', () => ({
  safeGet: () => null,
  safeSet: () => {},
  safeRemove: () => {},
}));
vi.mock('@/hooks/use-toast', () => ({ useToast: () => ({ toast: vi.fn() }) }));
vi.mock('@/components/financial-pulse/financial-pulse-widget', () => ({
  FinancialPulseWidget: () => null,
}));
vi.mock('@/lib/force-upgrade', () => ({ startForceUpgradePoller: () => {} }));

vi.mock('@/lib/queryClient', async () => {
  const actual = await vi.importActual('@/lib/queryClient');
  return { ...actual, apiRequest: vi.fn() };
});

import { apiRequest } from '@/lib/queryClient';
import { getCurrentUser } from '@/lib/impersonation';
const mockedApiRequest = apiRequest as ReturnType<typeof vi.fn>;
const mockedGetCurrentUser = getCurrentUser as ReturnType<typeof vi.fn>;

const now = Date.now();
const iso = (offsetMs: number) => new Date(now - offsetMs).toISOString();

// Default queue URL shape generated by the component with no filters applied:
// sort=age_desc&page=1&pageSize=50 (type=all is omitted when type is "all")
const DEFAULT_QUEUE_KEY = '/api/billing-workspace/queue?sort=age_desc&page=1&pageSize=50';
const WCB_QUEUE_KEY = '/api/billing-workspace/queue?type=wcb&sort=age_desc&page=1&pageSize=50';

const wcbQueueResponse = {
  items: [
    {
      id: 'wcb-1',
      type: 'wet_check_billing' as const,
      refId: 1,
      number: 'WCB-2026-001',
      customerId: 10,
      customerName: 'Acme Corp',
      technicianId: 100,
      technicianName: 'Tech A',
      total: 250,
      status: 'submitted',
      hasPhotos: null,
      flags: [],
      ageDays: 2,
      createdAt: iso(2 * 86400_000),
      href: '/wet-check-billings/1',
      wetCheckId: 50,
    },
  ],
  page: 1,
  pageSize: 50,
  total: 1,
};

const emptyQueueResponse = { items: [], page: 1, pageSize: 50, total: 0 };

const statusStrip = {
  awaitingApproval: 3,
  approvedThisWeek: 2,
  draftsLast24h: 1,
  quickbooks: {
    state: 'ok' as const,
    lastSyncAt: null,
    pendingSync: 0,
    overdueCount: 0,
    connectionStatus: 'connected',
    recentErrorCount: 0,
  },
};

function makeQc(defaultQueue: any = emptyQueueResponse, wcbQueue: any = emptyQueueResponse) {
  const qc = new QueryClient({
    defaultOptions: {
      queries: { retry: false, staleTime: Infinity, gcTime: Infinity },
      mutations: { retry: false },
    },
  });
  qc.setQueryData([DEFAULT_QUEUE_KEY], defaultQueue);
  qc.setQueryData([WCB_QUEUE_KEY], wcbQueue);
  qc.setQueryData(['/api/billing-workspace/status-strip'], statusStrip);
  qc.setQueryData(['/api/quickbooks/overdue-summary'], {
    overdueCount: 0, overdueAmount: 0, agingReportUrl: '/ar', asOf: new Date().toISOString(),
  });
  return qc;
}

async function renderPage(defaultQueue?: any, wcbQueue?: any) {
  const qc = makeQc(defaultQueue, wcbQueue);
  const { default: BillingWorkspace } = await import('./billing-workspace');
  let container!: HTMLElement;
  await act(async () => {
    ({ container } = render(
      <TooltipProvider>
        <QueryClientProvider client={qc}>
          <BillingWorkspace />
        </QueryClientProvider>
      </TooltipProvider>
    ));
  });
  return { qc, container };
}

describe('Billing Workspace — WCB Slice 6', () => {
  beforeEach(() => {
    vi.clearAllMocks();
    mockedGetCurrentUser.mockReturnValue({ id: 1, username: 'mgr', role: 'company_admin' });
  });

  it('renders a "Wet Check Billings" filter chip', async () => {
    await renderPage();
    const chip = screen.getByTestId('filter-chip-wet_check_billing');
    expect(chip).toBeTruthy();
    expect(chip.textContent).toContain('Wet Check Billings');
  });

  it('clicking the WCB chip activates it and uses type=wcb in the URL', async () => {
    await renderPage();
    const chip = screen.getByTestId('filter-chip-wet_check_billing');

    await act(async () => { fireEvent.click(chip); });

    // The chip should now be active-styled (has bg-blue-600 class)
    await waitFor(() => {
      expect(chip.className).toContain('bg-blue-600');
    }, { timeout: 2000 });
  });

  it('WCB queue row renders number, customer name, and tech name', async () => {
    await renderPage(wcbQueueResponse, wcbQueueResponse);

    await waitFor(() => {
      expect(screen.getByTestId('queue-row-wcb-1')).toBeTruthy();
    }, { timeout: 3000 });

    const row = screen.getByTestId('queue-row-wcb-1');
    expect(row.textContent).toContain('WCB-2026-001');
    expect(row.textContent).toContain('Acme Corp');
    expect(row.textContent).toContain('Tech A');
  });

  it('Approve button is hidden for billing_manager role on WCB rows', async () => {
    mockedGetCurrentUser.mockReturnValue({ id: 1, username: 'bm', role: 'billing_manager' });
    await renderPage(wcbQueueResponse, wcbQueueResponse);

    await waitFor(() => {
      expect(screen.getByTestId('queue-row-wcb-1')).toBeTruthy();
    }, { timeout: 3000 });

    await act(async () => {
      fireEvent.click(screen.getByTestId('queue-row-wcb-1'));
    });

    await waitFor(() => {
      expect(screen.queryByTestId('approve-button')).toBeNull();
    }, { timeout: 2000 });
  });

  it('Approve dispatches to /api/wet-checks/{wetCheckId}/approve for manager roles', async () => {
    mockedGetCurrentUser.mockReturnValue({ id: 1, username: 'mgr', role: 'company_admin' });
    mockedApiRequest.mockResolvedValueOnce({});

    await renderPage(wcbQueueResponse, wcbQueueResponse);

    await waitFor(() => {
      expect(screen.getByTestId('queue-row-wcb-1')).toBeTruthy();
    }, { timeout: 3000 });

    await act(async () => {
      fireEvent.click(screen.getByTestId('queue-row-wcb-1'));
    });

    await waitFor(() => {
      const buttons = screen.getAllByTestId('approve-button');
      expect(buttons.length).toBeGreaterThan(0);
    }, { timeout: 2000 });

    // Click the first approve button (inline pane or drawer — same action)
    await act(async () => {
      fireEvent.click(screen.getAllByTestId('approve-button')[0]);
    });

    await waitFor(() => {
      expect(mockedApiRequest).toHaveBeenCalledWith(
        '/api/wet-checks/50/approve',
        'POST',
        {},
      );
    }, { timeout: 3000 });
  });
});
